DROP TABLE IF EXISTS DRONE;
CREATE TABLE DRONE (
drone_id CHAR (36)  PRIMARY KEY,
serial_number VARCHAR(100) NOT NULL,
model VARCHAR(100) NOT NULL,
weight_limit INT NOT NULL,
battery_capacity INT NOT NULL,
state VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS MEDICATION;
CREATE TABLE MEDICATION (
medication_id CHAR (36)  PRIMARY KEY,
name VARCHAR(100) NOT NULL,
weight DOUBLE NOT NULL,
code VARCHAR(100) NOT NULL,
photo_url VARCHAR NOT NULL,
drone_id CHAR (36),
status VARCHAR(100)
);

DROP TABLE IF EXISTS HISTORY_LOG;
CREATE TABLE HISTORY_LOG (
log_id CHAR (36)  PRIMARY KEY,
drone_id CHAR (36),
battery_capacity INT NOT NULL,
created_at DATETIME NOT NULL
);
